<a href="https://www.kaggle.com/code/ayushkhaire/crypto-dataset-daily-updates-top-1000?scriptVersionId=219231772" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import requests as rq
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import os
from tqdm import tqdm
from kaggle_secrets import UserSecretsClient
from datetime import datetime
import json as js
import subprocess
import logging
import time
import shutil

# Yeasterday data :)

In [2]:
df = pd.read_csv('/kaggle/input/top-1000-cryptos-historical/1000_cryptos.csv')
df

,dates,symbol,open,close,high,low,volume,adj_close
0,2023-11-14 00:00:00,MUBI-USD,0.005282,0.006876,0.008202,0.003919,11217302.0,0.006876
1,2023-11-15 00:00:00,MUBI-USD,0.006884,0.007072,0.008159,0.004612,3123583.0,0.007072
2,2023-11-16 00:00:00,MUBI-USD,0.007064,0.015573,0.020994,0.006587,14072219.0,0.015573
3,2023-11-17 00:00:00,MUBI-USD,0.015589,0.019858,0.023690,0.014523,11558467.0,0.019858
4,2023-11-18 00:00:00,MUBI-USD,0.019876,0.031552,0.034176,0.017896,17315291.0,0.031552
...,...,...,...,...,...,...,...,...
2160351,2025-01-20 00:00:00,BDX-USD,0.078329,0.079321,0.081541,0.078075,7387912.0,0.079321
2160352,2025-01-21 00:00:00,BDX-USD,0.079321,0.078807,0.080057,0.078421,5932542.0,0.078807
2160353,2025-01-22 00:00:00,BDX-USD,0.078807,0.079031,0.079585,0.078565,5831809.0,0.079031
2160354,2025-01-23 00:00:00,BDX-USD,0.079031,0.078924,0.079380,0.078633,6533736.0,0.078924
2160355,2025-01-24 16:43:00,BDX-USD,0.078910,0.079150,0.079528,0.078328,5698108.0,0.079150

# Define headers

In [3]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
}

# Extract symbols

In [4]:
link = f'https://finance.yahoo.com/markets/crypto/all/?start=0&count=100'
link

'https://finance.yahoo.com/markets/crypto/all/?start=0&count=100'

# Get symbols and hit urls

In [5]:
resp_main_list = []
i = 0
for page in tqdm(range(20)):
    url = f'https://finance.yahoo.com/markets/crypto/all/?start={i*100}&count=100'
    r = rq.get(url,headers = headers)
    resp_main_list.append(r)
    i = i+1

100%|██████████| 20/20 [00:09<00:00,  2.10it/s]

In [6]:
symbol_list = []

for r in tqdm(resp_main_list):
    soup = BeautifulSoup(r.text,'html.parser')
    symbs= soup.find_all('span',{'class':'symbol'})
    for s in symbs:
        symbol_list.append(s.text)
        
print(len(symbol_list))
print(symbol_list[:20])

100%|██████████| 20/20 [00:08<00:00,  2.23it/s]

2520
['BTC-USD ', 'ETH-USD ', 'XRP-USD ', 'USDT-USD ', 'SOL-USD ', 'BNB-USD ', 'DOGE-USD ', 'USDC-USD ', 'ADA-USD ', 'STETH-USD ', 'WTRX-USD ', 'TRX-USD ', 'LINK-USD ', 'AVAX-USD ', 'WSTETH-USD ', 'OFFICIAL-TRUMP-USD ', 'WBTC-USD ', 'XLM-USD ', 'HBAR-USD ', 'TON11419-USD ']

# Now , get the link for today downloads from a tesla stock

### This we willl use to use "code" by yahoo finance to figure out dates

In [7]:
'''

llink1 = https://query1.finance.yahoo.com/v8/finance/chart/GLM-USD?events=capitalGain%7Cdiv%7Csplit&formatted=true&includeAdjustedClose=true&interval=1d&period1=1510185600&period2=1725897789&symbol=GLM-USD&userYfid=true&lang=en-US&region=US

here the period values are exactly same.
'''

# After research , i got they are unix timestamps in period . lets try it out !

import time

# Get current Unix timestamp
current_timestamp = int(time.time())

date_str = "2015-01-01"
date_obj = datetime.strptime(date_str, "%Y-%m-%d")
period1 = int(time.mktime(date_obj.timetuple()))

period2 = current_timestamp  

# Print the timestamps in the desired format
print(f"period1={period1}&period2={period2}")

period1=1420070400&period2=1737824702

# create stocks directory

In [8]:
os.mkdir('crypto_data')

# Download all files

In [9]:
def return_timestamp(unix_timestamps, date_format='%Y-%m-%d %H:%M:%S'):
    formatted_dates = []
    for ut in unix_timestamps:
        date = datetime.fromtimestamp(ut)
        formatted_date = date.strftime(date_format)
        formatted_dates.append(formatted_date)
    return formatted_dates

print(return_timestamp([1725898133]))

['2024-09-09 16:08:53']

In [10]:
symbol_list = set(symbol_list)
len(symbol_list)

2026

In [11]:
for stock in tqdm(symbol_list):
    stock = stock.replace(' ','')
    url = f'https://query1.finance.yahoo.com/v8/finance/chart/{stock}?events=capitalGain%7Cdiv%7Csplit&formatted=true&includeAdjustedClose=true&interval=1d&period1={period1}&period2={period2}&symbol={stock}&userYfid=true&lang=en-US&region=US'
    r = rq.get(url, headers=headers)
    if r.status_code == 200:
        with open(f"/kaggle/working/crypto_data/{stock}.json", "wb") as file:
            file.write(r.content)
#         print(f"File downloaded successfully : {stock}.json")
    else:
#         print(f"Failed to download file : {stock}.json")
        pass
#     time.sleep(3)

100%|██████████| 2026/2026 [04:32<00:00,  7.45it/s]

In [12]:
symbol_list_dir = os.listdir('/kaggle/working/crypto_data/')
len(symbol_list_dir)

2017

# Read a sample

In [13]:
# jsonf = pd.read_json(f'/kaggle/working/crypto_data/BTC-USD.json')
# jsondict = jsonf.to_dict()
# timestamp = jsondict.get('chart').get('result')[0].get('timestamp')
# sym = jsondict.get('chart').get('result')[0].get('meta').get('symbol')
# symbol = list(sym for s in range(len(timestamp)))
# low = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('low')
# high = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('high')
# volume = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('volume')
# open_ = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('open')
# close = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('close')
# adj_close = jsondict.get('chart').get('result')[0].get('indicators').get('adjclose')[0].get('adjclose')
# dates = return_timestamp(timestamp)
# tempdf = pd.DataFrame(
#     {
#     'dates':dates,
#     'symbol':symbol,
#     'open':open_,
#     'close':close,
#     'high':high,
#     'low':low,
#     'volume':volume,
#     'adj_close':adj_close
#     }
# )
# tempdf

# Work on dataset

In [14]:
megadf = pd.DataFrame()

In [15]:
for jso in tqdm(symbol_list_dir):
    jsonf = pd.read_json(f'/kaggle/working/crypto_data/{jso}')
    jsondict = jsonf.to_dict()
    
    # Safely get the timestamp and check if it's None
    timestamp = jsondict.get('chart').get('result')[0].get('timestamp')
    if timestamp is None:
        print(f"Missing timestamp for {jso}. Skipping this symbol.")
        continue  # Skip this iteration if timestamp is None
    
    # Proceed with the rest of the code after ensuring timestamp is not None
    low = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('low')
    sym = jsondict.get('chart').get('result')[0].get('meta').get('symbol')
    
    # Create a list of symbols based on the length of timestamp
    symbol = list(sym for s in range(len(timestamp)))
    
    high = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('high')
    volume = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('volume')
    open_ = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('open')
    close = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('close')
    adj_close = jsondict.get('chart').get('result')[0].get('indicators').get('adjclose')[0].get('adjclose')
    
    # Convert timestamp to dates
    dates = return_timestamp(timestamp)
    
    # Create a DataFrame
    tempdf = pd.DataFrame(
    {
        'dates': dates,
        'symbol': symbol,
        'open': open_,
        'close': close,
        'high': high,
        'low': low,
        'volume': volume,
        'adj_close': adj_close
    })
    
    # Concatenate the new data to the main DataFrame
    megadf = pd.concat([megadf, tempdf], ignore_index=True)

 45%|████▍     | 906/2017 [00:24<00:48, 22.70it/s]

Missing timestamp for Nasdaq.json. Skipping this symbol.

100%|██████████| 2017/2017 [01:41<00:00, 19.87it/s]

In [16]:
megadf['symbol'].nunique()

2016

In [17]:
first_date = megadf['dates'][0]
last_date = megadf['dates'].iloc[-1]

In [18]:
first_date,last_date

('2023-12-18 00:00:00', '2025-01-25 17:03:00')

In [19]:
megadf.dtypes

dates         object
symbol        object
open         float64
close        float64
high         float64
low          float64
volume       float64
adj_close    float64
dtype: object

In [20]:
megadf['dates'] = pd.to_datetime(megadf['dates'], format="mixed")

In [21]:
megadf.dtypes

dates        datetime64[ns]
symbol               object
open                float64
close               float64
high                float64
low                 float64
volume              float64
adj_close           float64
dtype: object

In [22]:
megadf

,dates,symbol,open,close,high,low,volume,adj_close
0,2023-12-18 00:00:00,P3D-USD,0.114540,0.041036,0.114547,0.035920,343779.0,0.041036
1,2023-12-19 00:00:00,P3D-USD,0.041036,0.038813,0.044767,0.038462,350972.0,0.038813
2,2023-12-20 00:00:00,P3D-USD,0.038814,0.044991,0.047010,0.038441,385053.0,0.044991
3,2023-12-21 00:00:00,P3D-USD,0.044992,0.043230,0.046625,0.040377,335177.0,0.043230
4,2023-12-22 00:00:00,P3D-USD,0.043229,0.039887,0.045954,0.039501,361208.0,0.039887
...,...,...,...,...,...,...,...,...
2149727,2025-01-21 00:00:00,BICO-USD,0.249848,0.260855,0.265930,0.238718,20118684.0,0.260855
2149728,2025-01-22 00:00:00,BICO-USD,0.260855,0.254467,0.265442,0.253951,12421994.0,0.254467
2149729,2025-01-23 00:00:00,BICO-USD,0.254467,0.252793,0.256352,0.242265,26736540.0,0.252793
2149730,2025-01-24 00:00:00,BICO-USD,0.252793,0.246247,0.258889,0.244095,23125051.0,0.246247
2149731,2025-01-25 17:03:00,BICO-USD,0.246257,0.248555,0.250931,0.242703,19290024.0,0.248555

In [23]:
os.mkdir('dataset')

In [24]:
megadf.to_csv(f'dataset/1000_cryptos.csv',index = False)

# final dataset

In [25]:
df = pd.read_csv(f'/kaggle/working/dataset/1000_cryptos.csv')

In [26]:
df

,dates,symbol,open,close,high,low,volume,adj_close
0,2023-12-18 00:00:00,P3D-USD,0.114540,0.041036,0.114547,0.035920,343779.0,0.041036
1,2023-12-19 00:00:00,P3D-USD,0.041036,0.038813,0.044767,0.038462,350972.0,0.038813
2,2023-12-20 00:00:00,P3D-USD,0.038814,0.044991,0.047010,0.038441,385053.0,0.044991
3,2023-12-21 00:00:00,P3D-USD,0.044992,0.043230,0.046625,0.040377,335177.0,0.043230
4,2023-12-22 00:00:00,P3D-USD,0.043229,0.039887,0.045954,0.039501,361208.0,0.039887
...,...,...,...,...,...,...,...,...
2149727,2025-01-21 00:00:00,BICO-USD,0.249848,0.260855,0.265930,0.238718,20118684.0,0.260855
2149728,2025-01-22 00:00:00,BICO-USD,0.260855,0.254467,0.265442,0.253951,12421994.0,0.254467
2149729,2025-01-23 00:00:00,BICO-USD,0.254467,0.252793,0.256352,0.242265,26736540.0,0.252793
2149730,2025-01-24 00:00:00,BICO-USD,0.252793,0.246247,0.258889,0.244095,23125051.0,0.246247
2149731,2025-01-25 17:03:00,BICO-USD,0.246257,0.248555,0.250931,0.242703,19290024.0,0.248555

# Upload Dataset

# User secrets

In [27]:
user_secrets = UserSecretsClient()
kaggle_apikey = user_secrets.get_secret("kaggle_apikey")
kaggle_username = user_secrets.get_secret("kaggle_username")

os.environ['KAGGLE_USERNAME'] = kaggle_username
os.environ['KAGGLE_KEY'] = kaggle_apikey

# Metadata file

In [28]:
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

print('Starting upload >>>>>>') 
print('Creating metadata file >>>>')
data = {
    "id": "ayushkhaire/top-1000-cryptos-historical"
}
metadata_file_location = '/kaggle/working/dataset/dataset-metadata.json' 
with open(metadata_file_location, 'w', encoding='utf-8') as metadata_file:
    js.dump(data, metadata_file)
print('Metadata file created')

Starting upload >>>>>>
Creating metadata file >>>>
Metadata file created

# upload

In [29]:
retries = 0
while retries < 5:
    try:
        command = "kaggle datasets version -p '/kaggle/working/dataset' -m 'Update' -r zip"
        subprocess.run(command, shell=True, check=True)
        logger.info("Upload complete")
        break
    except Exception as error:
        logger.error(f"Error from Kaggle: {error}")
        time.sleep(5)
        retries += 1

Starting upload for file 1000_cryptos.csv
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.17 / client 1.6.14)

100%|██████████| 269M/269M [00:03<00:00, 78.1MB/s]

Upload successful: 1000_cryptos.csv (269MB)
Dataset version is being created. Please check progress at https://www.kaggle.com/ayushkhaire/top-1000-cryptos-historical

In [30]:
shutil.rmtree('/kaggle/working/crypto_data')
shutil.rmtree('/kaggle/working/dataset')

# Thank you , and I will see you in next notebook :)