<a href="https://www.kaggle.com/code/ayushkhaire/crypto-dataset-daily-updates-top-2000?scriptVersionId=221296928" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import requests as rq
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import os
from tqdm import tqdm
from kaggle_secrets import UserSecretsClient
from datetime import datetime
import json as js
import subprocess
import logging
import time
import shutil

# Yeasterday data :)

In [2]:
df = pd.read_csv('/kaggle/input/top-1000-cryptos-historical/1000_cryptos.csv')
df

,dates,symbol,open,close,high,low,volume,adj_close
0,2020-11-19 00:00:00,ROSE-USD,0.068019,0.038197,0.068021,0.037390,38755818.0,0.038197
1,2020-11-20 00:00:00,ROSE-USD,0.038197,0.035878,0.042957,0.033579,17329732.0,0.035878
2,2020-11-21 00:00:00,ROSE-USD,0.035878,0.037811,0.039864,0.032672,16055734.0,0.037811
3,2020-11-22 00:00:00,ROSE-USD,0.037811,0.041603,0.042065,0.035263,10629011.0,0.041603
4,2020-11-23 00:00:00,ROSE-USD,0.041602,0.046931,0.053923,0.038529,24675225.0,0.046931
...,...,...,...,...,...,...,...,...
2177664,2025-01-30 00:00:00,TORO33670-USD,0.001832,0.001846,0.001941,0.001832,3094.0,0.001846
2177665,2025-01-31 00:00:00,TORO33670-USD,0.001846,0.001822,0.001846,0.001774,110.0,0.001822
2177666,2025-02-01 00:00:00,TORO33670-USD,0.001822,0.001705,0.001822,0.001705,15.0,0.001705
2177667,2025-02-02 00:00:00,TORO33670-USD,0.001705,0.001401,0.001705,0.001380,12696.0,0.001401
2177668,2025-02-03 16:38:00,TORO33670-USD,0.001400,0.001346,0.001400,0.001341,12932.0,0.001346

# Define headers

In [3]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
}

# Extract symbols

In [4]:
link = f'https://finance.yahoo.com/markets/crypto/all/?start=0&count=100'
link

'https://finance.yahoo.com/markets/crypto/all/?start=0&count=100'

# Get symbols and hit urls

In [5]:
resp_main_list = []
i = 0
for page in tqdm(range(20)):
    url = f'https://finance.yahoo.com/markets/crypto/all/?start={i*100}&count=100'
    r = rq.get(url,headers = headers)
    resp_main_list.append(r)
    i = i+1

100%|██████████| 20/20 [00:08<00:00,  2.27it/s]

In [6]:
symbol_list = []

for r in tqdm(resp_main_list):
    soup = BeautifulSoup(r.text,'html.parser')
    symbs= soup.find_all('span',{'class':'symbol'})
    for s in symbs:
        symbol_list.append(s.text)
        
print(len(symbol_list))
print(symbol_list[:20])

100%|██████████| 20/20 [00:09<00:00,  2.21it/s]

2520
['BTC-USD ', 'ETH-USD ', 'USDT-USD ', 'XRP-USD ', 'SOL-USD ', 'BNB-USD ', 'USDC-USD ', 'DOGE-USD ', 'STETH-USD ', 'ADA-USD ', 'WTRX-USD ', 'TRX-USD ', 'WBTC-USD ', 'LINK-USD ', 'WSTETH-USD ', 'AVAX-USD ', 'XLM-USD ', 'SUI20947-USD ', 'TON11419-USD ', 'WETH-USD ']

# Now , get the link for today downloads from a tesla stock

### This we willl use to use "code" by yahoo finance to figure out dates

In [7]:
'''

llink1 = https://query1.finance.yahoo.com/v8/finance/chart/GLM-USD?events=capitalGain%7Cdiv%7Csplit&formatted=true&includeAdjustedClose=true&interval=1d&period1=1510185600&period2=1725897789&symbol=GLM-USD&userYfid=true&lang=en-US&region=US

here the period values are exactly same.
'''

# After research , i got they are unix timestamps in period . lets try it out !

import time

# Get current Unix timestamp
current_timestamp = int(time.time())

date_str = "2015-01-01"
date_obj = datetime.strptime(date_str, "%Y-%m-%d")
period1 = int(time.mktime(date_obj.timetuple()))

period2 = current_timestamp  

# Print the timestamps in the desired format
print(f"period1={period1}&period2={period2}")

period1=1420070400&period2=1738932894

# create stocks directory

In [8]:
os.mkdir('crypto_data')

# Download all files

In [9]:
def return_timestamp(unix_timestamps, date_format='%Y-%m-%d %H:%M:%S'):
    formatted_dates = []
    for ut in unix_timestamps:
        date = datetime.fromtimestamp(ut)
        formatted_date = date.strftime(date_format)
        formatted_dates.append(formatted_date)
    return formatted_dates

print(return_timestamp([1725898133]))

['2024-09-09 16:08:53']

In [10]:
symbol_list = set(symbol_list)
len(symbol_list)

2024

In [11]:
for stock in tqdm(symbol_list):
    try:
        stock = stock.replace(' ','')
        url = f'https://query1.finance.yahoo.com/v8/finance/chart/{stock}?events=capitalGain%7Cdiv%7Csplit&formatted=true&includeAdjustedClose=true&interval=1d&period1={period1}&period2={period2}&symbol={stock}&userYfid=true&lang=en-US&region=US'
        r = rq.get(url, headers=headers)
        if r.status_code == 200:
            with open(f"/kaggle/working/crypto_data/{stock}.json", "wb") as file:
                file.write(r.content)
    #         print(f"File downloaded successfully : {stock}.json")
        else:
    #         print(f"Failed to download file : {stock}.json")
            pass
    #     time.sleep(3)
    except:
        continue

100%|██████████| 2024/2024 [05:20<00:00,  6.32it/s]

In [12]:
symbol_list_dir = os.listdir('/kaggle/working/crypto_data/')
len(symbol_list_dir)

2019

# Read a sample

In [13]:
# jsonf = pd.read_json(f'/kaggle/working/crypto_data/BTC-USD.json')
# jsondict = jsonf.to_dict()
# timestamp = jsondict.get('chart').get('result')[0].get('timestamp')
# sym = jsondict.get('chart').get('result')[0].get('meta').get('symbol')
# symbol = list(sym for s in range(len(timestamp)))
# low = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('low')
# high = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('high')
# volume = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('volume')
# open_ = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('open')
# close = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('close')
# adj_close = jsondict.get('chart').get('result')[0].get('indicators').get('adjclose')[0].get('adjclose')
# dates = return_timestamp(timestamp)
# tempdf = pd.DataFrame(
#     {
#     'dates':dates,
#     'symbol':symbol,
#     'open':open_,
#     'close':close,
#     'high':high,
#     'low':low,
#     'volume':volume,
#     'adj_close':adj_close
#     }
# )
# tempdf

# Work on dataset

In [14]:
megadf = pd.DataFrame()

In [15]:
for jso in tqdm(symbol_list_dir):
    jsonf = pd.read_json(f'/kaggle/working/crypto_data/{jso}')
    jsondict = jsonf.to_dict()
    
    # Safely get the timestamp and check if it's None
    timestamp = jsondict.get('chart').get('result')[0].get('timestamp')
    if timestamp is None:
        print(f"Missing timestamp for {jso}. Skipping this symbol.")
        continue  # Skip this iteration if timestamp is None
    
    # Proceed with the rest of the code after ensuring timestamp is not None
    low = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('low')
    sym = jsondict.get('chart').get('result')[0].get('meta').get('symbol')
    
    # Create a list of symbols based on the length of timestamp
    symbol = list(sym for s in range(len(timestamp)))
    
    high = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('high')
    volume = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('volume')
    open_ = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('open')
    close = jsondict.get('chart').get('result')[0].get('indicators').get('quote')[0].get('close')
    adj_close = jsondict.get('chart').get('result')[0].get('indicators').get('adjclose')[0].get('adjclose')
    
    # Convert timestamp to dates
    dates = return_timestamp(timestamp)
    
    # Create a DataFrame
    tempdf = pd.DataFrame(
    {
        'dates': dates,
        'symbol': symbol,
        'open': open_,
        'close': close,
        'high': high,
        'low': low,
        'volume': volume,
        'adj_close': adj_close
    })
    
    # Concatenate the new data to the main DataFrame
    megadf = pd.concat([megadf, tempdf], ignore_index=True)

100%|██████████| 2019/2019 [01:52<00:00, 18.00it/s]

In [16]:
megadf['symbol'].nunique()

2019

In [17]:
first_date = megadf['dates'][0]
last_date = megadf['dates'].iloc[-1]

In [18]:
first_date,last_date

('2022-11-07 00:00:00', '2025-02-07 12:51:00')

In [19]:
megadf.dtypes

dates         object
symbol        object
open         float64
close        float64
high         float64
low          float64
volume       float64
adj_close    float64
dtype: object

In [20]:
megadf['dates'] = pd.to_datetime(megadf['dates'], format="mixed")

In [21]:
megadf.dtypes

dates        datetime64[ns]
symbol               object
open                float64
close               float64
high                float64
low                 float64
volume              float64
adj_close           float64
dtype: object

In [22]:
megadf

,dates,symbol,open,close,high,low,volume,adj_close
0,2022-11-07 00:00:00,HFT22461-USD,2.547890,1.022048,2.580920,0.955428,594993320.0,1.022048
1,2022-11-08 00:00:00,HFT22461-USD,1.022225,0.636757,1.149525,0.617142,295660690.0,0.636757
2,2022-11-09 00:00:00,HFT22461-USD,0.636419,0.586944,0.671639,0.524610,109082724.0,0.586944
3,2022-11-10 00:00:00,HFT22461-USD,0.586871,0.662154,0.745413,0.569016,127748797.0,0.662154
4,2022-11-11 00:00:00,HFT22461-USD,0.662034,0.601299,0.682993,0.567872,70479584.0,0.601299
...,...,...,...,...,...,...,...,...
2164946,2025-02-03 00:00:00,BZR-USD,17.730639,17.865463,18.072075,14.127791,583841.0,17.865463
2164947,2025-02-04 00:00:00,BZR-USD,17.865463,16.971819,17.892960,16.356531,609669.0,16.971819
2164948,2025-02-05 00:00:00,BZR-USD,16.971819,17.309832,17.495518,16.774673,601276.0,17.309832
2164949,2025-02-06 00:00:00,BZR-USD,17.309832,16.675232,17.694695,16.548950,603226.0,16.675232
2164950,2025-02-07 12:51:00,BZR-USD,16.675232,17.110018,17.121096,16.580681,592945.0,17.110018

In [23]:
os.mkdir('dataset')

In [24]:
megadf.to_csv(f'dataset/1000_cryptos.csv',index = False)

# final dataset

In [25]:
df = pd.read_csv(f'/kaggle/working/dataset/1000_cryptos.csv')

In [26]:
df

,dates,symbol,open,close,high,low,volume,adj_close
0,2022-11-07 00:00:00,HFT22461-USD,2.547890,1.022048,2.580920,0.955428,594993320.0,1.022048
1,2022-11-08 00:00:00,HFT22461-USD,1.022225,0.636757,1.149525,0.617142,295660690.0,0.636757
2,2022-11-09 00:00:00,HFT22461-USD,0.636419,0.586944,0.671639,0.524610,109082724.0,0.586944
3,2022-11-10 00:00:00,HFT22461-USD,0.586871,0.662154,0.745413,0.569016,127748797.0,0.662154
4,2022-11-11 00:00:00,HFT22461-USD,0.662034,0.601299,0.682993,0.567872,70479584.0,0.601299
...,...,...,...,...,...,...,...,...
2164946,2025-02-03 00:00:00,BZR-USD,17.730639,17.865463,18.072075,14.127791,583841.0,17.865463
2164947,2025-02-04 00:00:00,BZR-USD,17.865463,16.971819,17.892960,16.356531,609669.0,16.971819
2164948,2025-02-05 00:00:00,BZR-USD,16.971819,17.309832,17.495518,16.774673,601276.0,17.309832
2164949,2025-02-06 00:00:00,BZR-USD,17.309832,16.675232,17.694695,16.548950,603226.0,16.675232
2164950,2025-02-07 12:51:00,BZR-USD,16.675232,17.110018,17.121096,16.580681,592945.0,17.110018

# Upload Dataset

# User secrets

In [27]:
user_secrets = UserSecretsClient()
kaggle_apikey = user_secrets.get_secret("kaggle_apikey")
kaggle_username = user_secrets.get_secret("kaggle_username")

os.environ['KAGGLE_USERNAME'] = kaggle_username
os.environ['KAGGLE_KEY'] = kaggle_apikey

# Metadata file

In [28]:
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

print('Starting upload >>>>>>') 
print('Creating metadata file >>>>')
data = {
    "id": "ayushkhaire/top-1000-cryptos-historical"
}
metadata_file_location = '/kaggle/working/dataset/dataset-metadata.json' 
with open(metadata_file_location, 'w', encoding='utf-8') as metadata_file:
    js.dump(data, metadata_file)
print('Metadata file created')

Starting upload >>>>>>
Creating metadata file >>>>
Metadata file created

# upload

In [29]:
retries = 0
while retries < 5:
    try:
        command = "kaggle datasets version -p '/kaggle/working/dataset' -m 'Update' -r zip"
        subprocess.run(command, shell=True, check=True)
        logger.info("Upload complete")
        break
    except Exception as error:
        logger.error(f"Error from Kaggle: {error}")
        time.sleep(5)
        retries += 1

Starting upload for file 1000_cryptos.csv
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.17 / client 1.6.14)

100%|██████████| 271M/271M [00:07<00:00, 39.4MB/s]

Upload successful: 1000_cryptos.csv (271MB)
Dataset version is being created. Please check progress at https://www.kaggle.com/ayushkhaire/top-1000-cryptos-historical

In [30]:
shutil.rmtree('/kaggle/working/crypto_data')
shutil.rmtree('/kaggle/working/dataset')

# Thank you , and I will see you in next notebook :)